import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Modals } from "@/components/modals";
import { SubscriptionAlert } from "@/features/subscription/components/subscription-alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design Art",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <SubscriptionAlert />
            <Modals />
            <Toaster
              richColors
              theme="light"
              position="bottom-right"
              duration={2000}
            />
            {children}
          </Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
